# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  filter_sets:
    squared_thumbnail_large:
      filters:
        thumbnail:
          size: [ 600, 370 ]
          mode: outbound
          allow_upscale: true
    squared_thumbnail_medium:
      filters:
        thumbnail:
          size: [ 300, 150 ]
          mode: outbound
          allow_upscale: true
    squared_thumbnail_small:
      filters:
        thumbnail:
          size: [ 100, 50 ]
          mode: outbound
          allow_upscale: true
    squared_thumbnail_card:
      filters:
        thumbnail:
          size: [ 224, 288 ]
          mode: outbound
          allow_upscale: true
    squared_thumbnail_gallery:
      filters:
        thumbnail:
          size: [ 500, 350 ]
          mode: outbound
          allow_upscale: true